name: query domain born date revv

on:
  workflow_dispatch:
    inputs:
      input_csv:
        description: csv filename
        required: true
        default: domains.csv
      domain_col:
        description: csv col name
        required: true
        default: domain
      batch_size:
        description: batch size
        required: false
        default: "1000"

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run borndate revved batch
        run: |
          python scripts/domain_borndate_revved.py
        env:
          input_csv: ${{ github.event.inputs.input_csv }}
          domain_col: ${{ github.event.inputs.domain_col }}
          BATCH_SIZE: ${{ github.event.inputs.batch_size }}

      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.run_id }}"
          prerelease: false
          title: "${{ github.run_id }}"
          files: |
            output/*
