name: query regisration date of semrush traffic domain
"on":
  workflow_dispatch:
    inputs:
      URL:
        description: csv filename
        type: enviroment
        required: true
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          sudo apt-get update      
          python -m pip install --upgrade pip
          pip install pandas  requests whodap whois21
      - name: run demo
        run: |
          mkdir output
          python  whois_checker_semrush.py > output/1.log
        env:
          URL: "${{ github.event.inputs.URL }}"
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.run_id }}"
          prerelease: false
          title: "${{ github.run_id }}"
          files: |
            output/*
