name: Install and Run Subwalker

on:
  workflow_dispatch:
    inputs:
      url:
        description: csv filename
        type: enviroment
        required: true

jobs:
  run-subwalker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone Subwalker
        run: git clone https://github.com/m8sec/subwalker.git

      - name: Change to Subwalker directory
        run: cd subwalker && ls

      - name: Set execute permission on subwalker script
        run: chmod +x subwalker.sh


      - name: Run subwalker with input URL
        run: |
         ./subwalker.sh  "${{ github.event.inputs.url }}"

          echo "Output saved to: /opt/subwalker/subwalker.txt"

      - name: Archive output
        uses: actions/upload-artifact@v2
        with:
          name: subwalker-output
          path: /opt/subwalker/subwalker.txt
