name: time cost
"on":
  workflow_dispatch:
        
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    environment: env
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          sudo apt-get update      
          python -m pip install --upgrade pip
          pip install gevent aiohttp urllib3 geventhttpclient
      - name: run demo
        run: |
          python  timecost.py
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.run_id }}"
          prerelease: false
          title: "${{ github.run_id }}"
          files: |
            output/*
